#!/usr/bin/env python

import os

home = os.getenv('HOME')
os.chdir(home + '/.bkrd/cur')
name = file('name').readline().strip()
num = int(file('num').readline())
max = int(file('max').readline())
cmd = 'dtt'
os.execvp(cmd,
    [cmd, '-d', name, '-i', 'num'] + [str(i) for i in xrange(num, max + 1)])
