#!/usr/bin/env python

import os

home = os.getenv('HOME')
os.chdir(home + '/.bkrd/cur')
num = int(file('num').readline())
max = int(file('max').readline())
cmd = 'dtt'
os.execvp(cmd, [cmd, '-i', 'num'] + [str(i) for i in xrange(num, max + 1)])
#
#
#i = file(home + '/p/dtt/bh/bh.'

##!/bin/sh
#set -e
#cd ~/.bkrd/cur
#exec dtt {`cat num`..`cat max`}

